version: '1.0.{build}'
image: Visual Studio 2022

build_script:
- ps: dotnet build -c Release

test_script:
- ps: dotnet test

before_build:
- ps: dotnet restore

after_build:
- ps: dotnet pack -c Release -o .\artifacts

artifacts:
- path: .\artifacts\*.nupkg
  name: NuGetPackage

deploy:
  provider: NuGet
  api_key: $(NUGET_API_KEY)
  artifact: NuGetPackage
  skip_cleanup: true